In [1]:
import pandas as pd
import numpy as np

* Load the excel file to a dataframe

In [2]:
raw_data = pd.read_excel("C:/Users/Arjun Janamatti/Downloads/Python question final.xlsx", index_col=[0,1,2], header=[0,1,2])
raw_data

US                                      China  \
                           state                    city           province   
                         Alabama Alaska Arizona Anniston Anchorage      Wan   
US    state    Alabama      1000   1010    1020     1030      1040     1050   
               Alaska       1015   1025    1035     1045      1055     1065   
               Arizona      1030   1040    1050     1060      1070     1080   
      city     Anniston     1045   1055    1065     1075      1085     1095   
               Anchorage    1060   1070    1080     1090      1100     1110   
China province Wan          1075   1085    1095     1105      1115     1125   
               Jing         1090   1100    1110     1120      1130     1140   
               Yu           1105   1115    1125     1135      1145     1155   
      city     Wan          1120   1130    1140     1150      1160     1170   
               Jing         1135   1145    1155     1165      1175     1185   
               Yu           1150   1160    1170     1180      1190     1200   
India state    Alabama      1165   1175    1185     1195      1205     1215   
               Punjab       1180   1190    1200     1210      1220     1230   

                                                        India         
                                      city              state         
                          Jing    Yu   Wan  Jing    Yu Kerala Punjab  
US    state    Alabama    1060  1070  1080  1090  1100   1110   1120  
               Alaska     1075  1085  1095  1105  1115   1125   1135  
               Arizona    1090  1100  1110  1120  1130   1140   1150  
      city     Anniston   1105  1115  1125  1135  1145   1155   1165  
               Anchorage  1120  1130  1140  1150  1160   1170   1180  
China province Wan        1135  1145  1155  1165  1175   1185   1195  
               Jing       1150  1160  1170  1180  1190   1200   1210  
               Yu         1165  1175  1185  1195  1205   1215   1225  
      city     Wan        1180  1190  1200  1210  1220   1230   1240  
               Jing       1195  1205  1215  1225  1235   1245   1255  
               Yu         1210  1220  1230  1240  1250   1260   1270  
India state    Alabama    1225  1235  1245  1255  1265   1275   1285  
               Punjab     1240  1250  1260  1270  1280   1290   1300

* Access vertical zones

In [3]:
raw_data_vertical = raw_data.xs('province',axis=1, level=1, drop_level=False)
vertical_zones = (raw_data_vertical.xs('Jing',axis=1, level=2, drop_level=False))
vertical_zones

China
                         province
                             Jing
US    state    Alabama       1060
               Alaska        1075
               Arizona       1090
      city     Anniston      1105
               Anchorage     1120
China province Wan           1135
               Jing          1150
               Yu            1165
      city     Wan           1180
               Jing          1195
               Yu            1210
India state    Alabama       1225
               Punjab        1240

* Splitting the vertical zone values based on their country

In [4]:
zones_vertical = []
rows_list_level_0 = (vertical_zones.index).get_level_values(0).unique()
for i in range(len(rows_list_level_0)):
    if (vertical_zones.index).get_level_values(0).unique()[i] == rows_list_level_0[i]:
        zones_vertical.append((vertical_zones.loc[[rows_list_level_0[i]]]).values)
zones_vertical

[array([[1060],
        [1075],
        [1090],
        [1105],
        [1120]], dtype=int64),
 array([[1135],
        [1150],
        [1165],
        [1180],
        [1195],
        [1210]], dtype=int64),
 array([[1225],
        [1240]], dtype=int64)]

* Adding the co-effecients

In [5]:
vertical_zone_coeffecients = [[0.25, 0.25, 0.5],[0.15, 0.15, 0.7],[0.1, 0.1, 0.8]]

* Perform calculations
* The multiplication is not element wise, hence we will again have to arrange this matrix

In [6]:
new_vertical_values = []
new_list_vertical = []
for i in range(len(zones_vertical)):
    for k in range(len(vertical_zone_coeffecients[i])):
        new_list_vertical.append(zones_vertical[i] * vertical_zone_coeffecients[i][k])
#     print((np.array(new_list)))
    new_vertical_values.extend(new_list_vertical)
    new_list_vertical.clear()
new_vertical_values

[array([[265.  ],
        [268.75],
        [272.5 ],
        [276.25],
        [280.  ]]),
 array([[265.  ],
        [268.75],
        [272.5 ],
        [276.25],
        [280.  ]]),
 array([[530. ],
        [537.5],
        [545. ],
        [552.5],
        [560. ]]),
 array([[170.25],
        [172.5 ],
        [174.75],
        [177.  ],
        [179.25],
        [181.5 ]]),
 array([[170.25],
        [172.5 ],
        [174.75],
        [177.  ],
        [179.25],
        [181.5 ]]),
 array([[794.5],
        [805. ],
        [815.5],
        [826. ],
        [836.5],
        [847. ]]),
 array([[122.5],
        [124. ]]),
 array([[122.5],
        [124. ]]),
 array([[980.],
        [992.]])]

* Rearrangement of the array as per our shape requirement

In [7]:
vertical_zones_1 = []
for i in range(len(vertical_zone_coeffecients)):
    if i+6 < len(new_vertical_values):
        vertical_zones_1.append(np.hstack(np.r_[new_vertical_values[i],new_vertical_values[i+3], new_vertical_values[i+6]]))
vertical_zones_1

[array([265.  , 268.75, 272.5 , 276.25, 280.  , 170.25, 172.5 , 174.75,
        177.  , 179.25, 181.5 , 122.5 , 124.  ]),
 array([265.  , 268.75, 272.5 , 276.25, 280.  , 170.25, 172.5 , 174.75,
        177.  , 179.25, 181.5 , 122.5 , 124.  ]),
 array([530. , 537.5, 545. , 552.5, 560. , 794.5, 805. , 815.5, 826. ,
        836.5, 847. , 980. , 992. ])]

* Adding the results to the dataframe, I will copy the original dataframe to another name for simplicity

In [8]:
raw_data_vertical = raw_data.copy(deep=True)
for i in range(len(vertical_zones_1)):
    raw_data_vertical["China","province","level_2_{}".format(i)] = vertical_zones_1[i]
raw_data_vertical

US                                      China  \
                           state                    city           province   
                         Alabama Alaska Arizona Anniston Anchorage      Wan   
US    state    Alabama      1000   1010    1020     1030      1040     1050   
               Alaska       1015   1025    1035     1045      1055     1065   
               Arizona      1030   1040    1050     1060      1070     1080   
      city     Anniston     1045   1055    1065     1075      1085     1095   
               Anchorage    1060   1070    1080     1090      1100     1110   
China province Wan          1075   1085    1095     1105      1115     1125   
               Jing         1090   1100    1110     1120      1130     1140   
               Yu           1105   1115    1125     1135      1145     1155   
      city     Wan          1120   1130    1140     1150      1160     1170   
               Jing         1135   1145    1155     1165      1175     1185   
               Yu           1150   1160    1170     1180      1190     1200   
India state    Alabama      1165   1175    1185     1195      1205     1215   
               Punjab       1180   1190    1200     1210      1220     1230   

                                                        India         \
                                      city              state          
                          Jing    Yu   Wan  Jing    Yu Kerala Punjab   
US    state    Alabama    1060  1070  1080  1090  1100   1110   1120   
               Alaska     1075  1085  1095  1105  1115   1125   1135   
               Arizona    1090  1100  1110  1120  1130   1140   1150   
      city     Anniston   1105  1115  1125  1135  1145   1155   1165   
               Anchorage  1120  1130  1140  1150  1160   1170   1180   
China province Wan        1135  1145  1155  1165  1175   1185   1195   
               Jing       1150  1160  1170  1180  1190   1200   1210   
               Yu         1165  1175  1185  1195  1205   1215   1225   
      city     Wan        1180  1190  1200  1210  1220   1230   1240   
               Jing       1195  1205  1215  1225  1235   1245   1255   
               Yu         1210  1220  1230  1240  1250   1260   1270   
India state    Alabama    1225  1235  1245  1255  1265   1275   1285   
               Punjab     1240  1250  1260  1270  1280   1290   1300   

                             China                      
                          province                      
                         level_2_0 level_2_1 level_2_2  
US    state    Alabama      265.00    265.00     530.0  
               Alaska       268.75    268.75     537.5  
               Arizona      272.50    272.50     545.0  
      city     Anniston     276.25    276.25     552.5  
               Anchorage    280.00    280.00     560.0  
China province Wan          170.25    170.25     794.5  
               Jing         172.50    172.50     805.0  
               Yu           174.75    174.75     815.5  
      city     Wan          177.00    177.00     826.0  
               Jing         179.25    179.25     836.5  
               Yu           181.50    181.50     847.0  
India state    Alabama      122.50    122.50     980.0  
               Punjab       124.00    124.00     992.0

#### Access the first level

In [9]:
raw_data.loc[["China"]]

US                                      China        \
                      state                    city           province         
                    Alabama Alaska Arizona Anniston Anchorage      Wan  Jing   
China province Wan     1075   1085    1095     1105      1115     1125  1135   
               Jing    1090   1100    1110     1120      1130     1140  1150   
               Yu      1105   1115    1125     1135      1145     1155  1165   
      city     Wan     1120   1130    1140     1150      1160     1170  1180   
               Jing    1135   1145    1155     1165      1175     1185  1195   
               Yu      1150   1160    1170     1180      1190     1200  1210   

                                             India         
                           city              state         
                       Yu   Wan  Jing    Yu Kerala Punjab  
China province Wan   1145  1155  1165  1175   1185   1195  
               Jing  1160  1170  1180  1190   1200   1210  
               Yu    1175  1185  1195  1205   1215   1225  
      city     Wan   1190  1200  1210  1220   1230   1240  
               Jing  1205  1215  1225  1235   1245   1255  
               Yu    1220  1230  1240  1250   1260   1270

#### Access the third level

In [10]:
raw_data.xs('Jing',axis=0, level=2, drop_level=False)

US                                      China        \
                      state                    city           province         
                    Alabama Alaska Arizona Anniston Anchorage      Wan  Jing   
China province Jing    1090   1100    1110     1120      1130     1140  1150   
      city     Jing    1135   1145    1155     1165      1175     1185  1195   

                                             India         
                           city              state         
                       Yu   Wan  Jing    Yu Kerala Punjab  
China province Jing  1160  1170  1180  1190   1200   1210  
      city     Jing  1205  1215  1225  1235   1245   1255

#### Extract relevant level

In [11]:
raw_data_1 = raw_data.xs('province',axis=0, level=1, drop_level=False)
raw_data_1

US                                      China        \
                      state                    city           province         
                    Alabama Alaska Arizona Anniston Anchorage      Wan  Jing   
China province Wan     1075   1085    1095     1105      1115     1125  1135   
               Jing    1090   1100    1110     1120      1130     1140  1150   
               Yu      1105   1115    1125     1135      1145     1155  1165   

                                             India         
                           city              state         
                       Yu   Wan  Jing    Yu Kerala Punjab  
China province Wan   1145  1155  1165  1175   1185   1195  
               Jing  1160  1170  1180  1190   1200   1210  
               Yu    1175  1185  1195  1205   1215   1225

#### Accessing the horizontal rows

In [12]:
horizontal_zones = (raw_data_1.xs('Jing',axis=0, level=2, drop_level=False))
horizontal_zones_array = horizontal_zones.values
horizontal_zones_array

array([[1090, 1100, 1110, 1120, 1130, 1140, 1150, 1160, 1170, 1180, 1190,
        1200, 1210]], dtype=int64)

#### Extract the values for each country

In [13]:
zones = []
columns_list_level_0 = (horizontal_zones.columns).get_level_values(0).unique()
for i in range(len(columns_list_level_0)):
    if (horizontal_zones.columns).get_level_values(0).unique()[i] == columns_list_level_0[i]:
        zones.append((horizontal_zones[[columns_list_level_0[i]]]).values)
zones

[array([[1090, 1100, 1110, 1120, 1130]], dtype=int64),
 array([[1140, 1150, 1160, 1170, 1180, 1190]], dtype=int64),
 array([[1200, 1210]], dtype=int64)]

In [14]:
zone_coeffecients = [[0.2, 0.4, 0.4],[0.3, 0.3, 0.4],[0.1, 0.1, 0.8]]

Perform calculations

In [15]:
new_horizontal_values = []
new_list = []
for i in range(len(zones)):
    for k in range(len(zone_coeffecients)):
        new_list.append(zones[i] * zone_coeffecients[i][k])
#     print((np.array(new_list)))
    new_horizontal_values.extend(new_list)
    new_list.clear()
new_horizontal_values

[array([[218., 220., 222., 224., 226.]]),
 array([[436., 440., 444., 448., 452.]]),
 array([[436., 440., 444., 448., 452.]]),
 array([[342., 345., 348., 351., 354., 357.]]),
 array([[342., 345., 348., 351., 354., 357.]]),
 array([[456., 460., 464., 468., 472., 476.]]),
 array([[120., 121.]]),
 array([[120., 121.]]),
 array([[960., 968.]])]

#### Arrange the values in form of rows to be added to the main data

In [16]:
horizontal_zones_1 = []
for i in range(len(zone_coeffecients)):
    if i+6 < len(new_horizontal_values):
        horizontal_zones_1.append(np.hstack(np.c_[new_horizontal_values[i],new_horizontal_values[i+3], new_horizontal_values[i+6]]))
horizontal_zones_1

[array([218., 220., 222., 224., 226., 342., 345., 348., 351., 354., 357.,
        120., 121.]),
 array([436., 440., 444., 448., 452., 342., 345., 348., 351., 354., 357.,
        120., 121.]),
 array([436., 440., 444., 448., 452., 456., 460., 464., 468., 472., 476.,
        960., 968.])]

In [17]:
raw_data_horizontal = raw_data.copy(deep=True)
for i in range(len(horizontal_zones_1)):
    row_to_append = pd.Series(horizontal_zones_1[i])
#     if i + 1 < len(new_horizontal_values_1):
    raw_data_horizontal.loc[((horizontal_zones.index.get_level_values(0).unique())[0], (horizontal_zones.index.get_level_values(1).unique())[0], "new_row_1_1_{}".format(i))] = row_to_append.values
raw_data_horizontal

US                                     \
                               state                     city             
                             Alabama  Alaska Arizona Anniston Anchorage   
US    state    Alabama        1000.0  1010.0  1020.0   1030.0    1040.0   
               Alaska         1015.0  1025.0  1035.0   1045.0    1055.0   
               Arizona        1030.0  1040.0  1050.0   1060.0    1070.0   
      city     Anniston       1045.0  1055.0  1065.0   1075.0    1085.0   
               Anchorage      1060.0  1070.0  1080.0   1090.0    1100.0   
China province Wan            1075.0  1085.0  1095.0   1105.0    1115.0   
               Jing           1090.0  1100.0  1110.0   1120.0    1130.0   
               Yu             1105.0  1115.0  1125.0   1135.0    1145.0   
      city     Wan            1120.0  1130.0  1140.0   1150.0    1160.0   
               Jing           1135.0  1145.0  1155.0   1165.0    1175.0   
               Yu             1150.0  1160.0  1170.0   1180.0    1190.0   
India state    Alabama        1165.0  1175.0  1185.0   1195.0    1205.0   
               Punjab         1180.0  1190.0  1200.0   1210.0    1220.0   
China province new_row_1_1_0   218.0   220.0   222.0    224.0     226.0   
               new_row_1_1_1   436.0   440.0   444.0    448.0     452.0   
               new_row_1_1_2   436.0   440.0   444.0    448.0     452.0   

                                China                                          \
                             province                    city                   
                                  Wan    Jing      Yu     Wan    Jing      Yu   
US    state    Alabama         1050.0  1060.0  1070.0  1080.0  1090.0  1100.0   
               Alaska          1065.0  1075.0  1085.0  1095.0  1105.0  1115.0   
               Arizona         1080.0  1090.0  1100.0  1110.0  1120.0  1130.0   
      city     Anniston        1095.0  1105.0  1115.0  1125.0  1135.0  1145.0   
               Anchorage       1110.0  1120.0  1130.0  1140.0  1150.0  1160.0   
China province Wan             1125.0  1135.0  1145.0  1155.0  1165.0  1175.0   
               Jing            1140.0  1150.0  1160.0  1170.0  1180.0  1190.0   
               Yu              1155.0  1165.0  1175.0  1185.0  1195.0  1205.0   
      city     Wan             1170.0  1180.0  1190.0  1200.0  1210.0  1220.0   
               Jing            1185.0  1195.0  1205.0  1215.0  1225.0  1235.0   
               Yu              1200.0  1210.0  1220.0  1230.0  1240.0  1250.0   
India state    Alabama         1215.0  1225.0  1235.0  1245.0  1255.0  1265.0   
               Punjab          1230.0  1240.0  1250.0  1260.0  1270.0  1280.0   
China province new_row_1_1_0    342.0   345.0   348.0   351.0   354.0   357.0   
               new_row_1_1_1    342.0   345.0   348.0   351.0   354.0   357.0   
               new_row_1_1_2    456.0   460.0   464.0   468.0   472.0   476.0   

                               India          
                               state          
                              Kerala  Punjab  
US    state    Alabama        1110.0  1120.0  
               Alaska         1125.0  1135.0  
               Arizona        1140.0  1150.0  
      city     Anniston       1155.0  1165.0  
               Anchorage      1170.0  1180.0  
China province Wan            1185.0  1195.0  
               Jing           1200.0  1210.0  
               Yu             1215.0  1225.0  
      city     Wan            1230.0  1240.0  
               Jing           1245.0  1255.0  
               Yu             1260.0  1270.0  
India state    Alabama        1275.0  1285.0  
               Punjab         1290.0  1300.0  
China province new_row_1_1_0   120.0   121.0  
               new_row_1_1_1   120.0   121.0  
               new_row_1_1_2   960.0   968.0

Zone_7 options

In [22]:
option_select = input("Enter either '1' for selecting option_1 or '2' for selectin option_2: ")
if option_select == "1":
    print("option_1 is selected")
    final_option_coeffecient = [[0.15,0.15,0.7],[0.15,0.15,0.7],[0.15,0.15,0.7]]
elif option_select == "2":
    print("option_2 is selected")
    final_option_coeffecient = [[1,0,0],[0,1,0],[0,0,1]]

Enter either '1' for selecting option_1 or '2' for selectin option_2: 2
option_2 is selected


Extract the value for calculations

In [23]:
final_option = (raw_data_horizontal.xs('China',axis=1, level=0, drop_level=False))
final_option = (final_option["China","province","Jing"]).values
final_option = final_option[-3:]
final_option

array([345., 345., 460.])

Perform the calculations

In [24]:
new_final_option_values = []
new_list_final_option = []
for i in range(len(final_option)):
    for k in range(len(final_option_coeffecient)):
        new_list_final_option.append(final_option[i] * final_option_coeffecient[i][k])
#     print((np.array(new_list_final_option)))
    new_final_option_values.extend(new_list_final_option)
    new_list_final_option.clear()
new_final_option_values = np.split(np.array(new_final_option_values),len(final_option))
new_final_option_values

[array([345.,   0.,   0.]),
 array([  0., 345.,   0.]),
 array([  0.,   0., 460.])]

Now lets add the zone 7 to horizontal values

In [25]:
horizontal_zones_2 = []
for i in range(len(horizontal_zones_1)):
    horizontal_zones_2.append(np.r_[horizontal_zones_1[i],new_final_option_values[i]])
horizontal_zones_2

[array([218., 220., 222., 224., 226., 342., 345., 348., 351., 354., 357.,
        120., 121., 345.,   0.,   0.]),
 array([436., 440., 444., 448., 452., 342., 345., 348., 351., 354., 357.,
        120., 121.,   0., 345.,   0.]),
 array([436., 440., 444., 448., 452., 456., 460., 464., 468., 472., 476.,
        960., 968.,   0.,   0., 460.])]

### Final RESULT DATAFRAME

In [26]:
raw_data_horizontal = raw_data_vertical.copy(deep=True)
for i in range(len(horizontal_zones_1)):
    row_to_append = pd.Series(horizontal_zones_2[i])
#     if i + 1 < len(new_horizontal_values_1):
    raw_data_horizontal.loc[((horizontal_zones.index.get_level_values(0).unique())[0], (horizontal_zones.index.get_level_values(1).unique())[0], "new_row_1_1_{}".format(i))] = row_to_append.values
raw_data_horizontal = raw_data_horizontal.drop([("China","province","Jing")], axis=0)
raw_data_horizontal = raw_data_horizontal.drop([("China","province","Jing")], axis=1)
raw_data_horizontal

US                                     \
                               state                     city             
                             Alabama  Alaska Arizona Anniston Anchorage   
US    state    Alabama        1000.0  1010.0  1020.0   1030.0    1040.0   
               Alaska         1015.0  1025.0  1035.0   1045.0    1055.0   
               Arizona        1030.0  1040.0  1050.0   1060.0    1070.0   
      city     Anniston       1045.0  1055.0  1065.0   1075.0    1085.0   
               Anchorage      1060.0  1070.0  1080.0   1090.0    1100.0   
China province Wan            1075.0  1085.0  1095.0   1105.0    1115.0   
               Yu             1105.0  1115.0  1125.0   1135.0    1145.0   
      city     Wan            1120.0  1130.0  1140.0   1150.0    1160.0   
               Jing           1135.0  1145.0  1155.0   1165.0    1175.0   
               Yu             1150.0  1160.0  1170.0   1180.0    1190.0   
India state    Alabama        1165.0  1175.0  1185.0   1195.0    1205.0   
               Punjab         1180.0  1190.0  1200.0   1210.0    1220.0   
China province new_row_1_1_0   218.0   220.0   222.0    224.0     226.0   
               new_row_1_1_1   436.0   440.0   444.0    448.0     452.0   
               new_row_1_1_2   436.0   440.0   444.0    448.0     452.0   

                                China                                   India  \
                             province            city                   state   
                                  Wan      Yu     Wan    Jing      Yu  Kerala   
US    state    Alabama         1050.0  1070.0  1080.0  1090.0  1100.0  1110.0   
               Alaska          1065.0  1085.0  1095.0  1105.0  1115.0  1125.0   
               Arizona         1080.0  1100.0  1110.0  1120.0  1130.0  1140.0   
      city     Anniston        1095.0  1115.0  1125.0  1135.0  1145.0  1155.0   
               Anchorage       1110.0  1130.0  1140.0  1150.0  1160.0  1170.0   
China province Wan             1125.0  1145.0  1155.0  1165.0  1175.0  1185.0   
               Yu              1155.0  1175.0  1185.0  1195.0  1205.0  1215.0   
      city     Wan             1170.0  1190.0  1200.0  1210.0  1220.0  1230.0   
               Jing            1185.0  1205.0  1215.0  1225.0  1235.0  1245.0   
               Yu              1200.0  1220.0  1230.0  1240.0  1250.0  1260.0   
India state    Alabama         1215.0  1235.0  1245.0  1255.0  1265.0  1275.0   
               Punjab          1230.0  1250.0  1260.0  1270.0  1280.0  1290.0   
China province new_row_1_1_0    342.0   348.0   351.0   354.0   357.0   120.0   
               new_row_1_1_1    342.0   348.0   351.0   354.0   357.0   120.0   
               new_row_1_1_2    456.0   464.0   468.0   472.0   476.0   960.0   

                                         China                      
                                      province                      
                              Punjab level_2_0 level_2_1 level_2_2  
US    state    Alabama        1120.0    265.00    265.00     530.0  
               Alaska         1135.0    268.75    268.75     537.5  
               Arizona        1150.0    272.50    272.50     545.0  
      city     Anniston       1165.0    276.25    276.25     552.5  
               Anchorage      1180.0    280.00    280.00     560.0  
China province Wan            1195.0    170.25    170.25     794.5  
               Yu             1225.0    174.75    174.75     815.5  
      city     Wan            1240.0    177.00    177.00     826.0  
               Jing           1255.0    179.25    179.25     836.5  
               Yu             1270.0    181.50    181.50     847.0  
India state    Alabama        1285.0    122.50    122.50     980.0  
               Punjab         1300.0    124.00    124.00     992.0  
China province new_row_1_1_0   121.0    345.00      0.00       0.0  
               new_row_1_1_1   121.0      0.00    345.00       0.0  
               new_row_1_1_2   968.0      0.00     

In [28]:
raw_data_horizontal.sort_index(inplace=True)
raw_data_horizontal.sort_index(axis=1, inplace=True)

In [29]:
raw_data_horizontal

China                                   \
                                city                 province           
                                Jing     Wan      Yu      Wan      Yu   
China city     Jing           1225.0  1215.0  1235.0   1185.0  1205.0   
               Wan            1210.0  1200.0  1220.0   1170.0  1190.0   
               Yu             1240.0  1230.0  1250.0   1200.0  1220.0   
      province Wan            1165.0  1155.0  1175.0   1125.0  1145.0   
               Yu             1195.0  1185.0  1205.0   1155.0  1175.0   
               new_row_1_1_0   354.0   351.0   357.0    342.0   348.0   
               new_row_1_1_1   354.0   351.0   357.0    342.0   348.0   
               new_row_1_1_2   472.0   468.0   476.0    456.0   464.0   
India state    Alabama        1255.0  1245.0  1265.0   1215.0  1235.0   
               Punjab         1270.0  1260.0  1280.0   1230.0  1250.0   
US    city     Anchorage      1150.0  1140.0  1160.0   1110.0  1130.0   
               Anniston       1135.0  1125.0  1145.0   1095.0  1115.0   
      state    Alabama        1090.0  1080.0  1100.0   1050.0  1070.0   
               Alaska         1105.0  1095.0  1115.0   1065.0  1085.0   
               Arizona        1120.0  1110.0  1130.0   1080.0  1100.0   

                                                             India          \
                                                             state           
                             level_2_0 level_2_1 level_2_2  Kerala  Punjab   
China city     Jing             179.25    179.25     836.5  1245.0  1255.0   
               Wan              177.00    177.00     826.0  1230.0  1240.0   
               Yu               181.50    181.50     847.0  1260.0  1270.0   
      province Wan              170.25    170.25     794.5  1185.0  1195.0   
               Yu               174.75    174.75     815.5  1215.0  1225.0   
               new_row_1_1_0    345.00      0.00       0.0   120.0   121.0   
               new_row_1_1_1      0.00    345.00       0.0   120.0   121.0   
               new_row_1_1_2      0.00      0.00     460.0   960.0   968.0   
India state    Alabama          122.50    122.50     980.0  1275.0  1285.0   
               Punjab           124.00    124.00     992.0  1290.0  1300.0   
US    city     Anchorage        280.00    280.00     560.0  1170.0  1180.0   
               Anniston         276.25    276.25     552.5  1155.0  1165.0   
      state    Alabama          265.00    265.00     530.0  1110.0  1120.0   
               Alaska           268.75    268.75     537.5  1125.0  1135.0   
               Arizona          272.50    272.50     545.0  1140.0  1150.0   

                                    US                                   
                                  city            state                  
                             Anchorage Anniston Alabama  Alaska Arizona  
China city     Jing             1175.0   1165.0  1135.0  1145.0  1155.0  
               Wan              1160.0   1150.0  1120.0  1130.0  1140.0  
               Yu               1190.0   1180.0  1150.0  1160.0  1170.0  
      province Wan              1115.0   1105.0  1075.0  1085.0  1095.0  
               Yu               1145.0   1135.0  1105.0  1115.0  1125.0  
               new_row_1_1_0     226.0    224.0   218.0   220.0   222.0  
               new_row_1_1_1     452.0    448.0   436.0   440.0   444.0  
               new_row_1_1_2     452.0    448.0   436.0   440.0   444.0  
India state    Alabama          1205.0   1195.0  1165.0  1175.0  1185.0  
               Punjab           1220.0   1210.0  1180.0  1190.0  1200.0  
US    city     Anchorage        1100.0   1090.0  1060.0  1070.0  1080.0  
               Anniston         1085.0   1075.0  1045.0  1055.0  1065.0  
      state    Alabama          1040.0   1030.0  1000.0  1010.0  1020.0  
               Alaska           1055.0   1045.0  1015.0  1025.0  1035.0  
               Arizona          1070.0   1060.0  1030